### ISSUE TITLE
Security and User Authentication

### ISSUE THREAD

**Issue by NamanSudan** [NamanSudan/blogFrog#16]
1. Sign users in 
2. Sign users out
3. Create new accounts

**Comment by NamanSudan** [comment]
Step1: Figure out how to get the information from the user-filled fields to our backend.

**Comment by NamanSudan** [comment]
Step2: Create users, store them in a DB, hash their password, validate their usernames and emails (check if they are taken, email verification)

**Comment by NamanSudan** [comment]
For Step1, need to update auth.py file to allow POST requests

**Comment by NamanSudan** [comment]
Step1: completed. Now we are able to get the data from the URLs or those endpoints to the backend.

**Comment by NamanSudan** [comment]
For Step2, need to go to init.py file to set up the db

**Comment by NamanSudan** [comment]
Step2 status update: added create_database(app) function to the init.py file, added the db path, called the db init app, called the create_db function

**Comment by NamanSudan** [comment]
Step3: DB is completely empty right now and that is because tables and models still need to be created for the db.
Tasks:
1. Create models.py file in the website folder. In the context of relational dbs, models are just tables.
2. Define User model function in models.py file
3. The user model should keep track of id (primary key), email (unique), username (unique), password, date created.

**Comment by NamanSudan** [comment]
Step3: completed. imported the user module into the __init__.py file to make sure that the User Model is a part of our Flask application and so that the application can successfully create the database.

**Comment by NamanSudan** [comment]
Step4: Set-up the Login Manager:
1. it helps load a session for an already signed-in user by remembering its id.

**Comment by NamanSudan** [comment]
Step5: Create a user account when someone signs-up and how to login to that user account

**Comment by NamanSudan** [comment]
Step5 status update:
1. Within the sign-up function in the auth.py file, check for request method
2. Check if user already exists by checking for email and username
3. Check if password1 == password2
4. Check if length of username & password meet minimum length requirements
5. Else, add user to database. Password not hashed right now. Step 5, point 5 needs to be worked on. Need to hash password for security issue.

**Comment by NamanSudan** [comment]
Step 5 point 5: found a way to hash the password. 
Step5 status update: completed.

**Comment by NamanSudan** [comment]
Step 5 point 5: found a way to hash the password. 
Step5 status update: completed.

**Comment by NamanSudan** [comment]
Step6: Signing-in users:
1. add if request is POST:
2. if user exists based on email:
3. if password is correct:
4. login the user, redirect to home page

Going back to Step5:
1. Login the user once the user has signed-up

**Comment by NamanSudan** [comment]
Step6: Signing-in users:
1. add if request is POST:
2. if user exists based on email:
3. if password is correct:
4. login the user, redirect to home page
5. Else: incorrect password
6. Else: email doesn't exist 

Going back to Step5:
1. Login the user once the user has signed-up

**Comment by NamanSudan** [comment]
Step7: Sign-out user:
1. add if signed-in decorator to make sure that only a user that is signed-in is able to access that page
2. add logout command

**Comment by NamanSudan** [comment]
Step8: Output our flash messages:
1. make changes to base.html

**Comment by NamanSudan** [comment]
Step8: completed. Pls review @avb7

**Comment by avb7** [comment]
Send me the pull request to review

**Comment by NamanSudan** [comment]
How do I send it to you?

**Comment by NamanSudan** [comment]
I just did the following commands on terminal:

git checkout -b feature/security
git add*
git status
git push -u origin feature/security

Just realized that I forgot to commit the changes before pushing them.
Don't see any updates on github

**Comment by avb7** [comment]
We will be moving this effort to a new issue #21 that will encompass comprehensive user auth features
