### ISSUE TITLE
Setting up PostgreSQL on AWS RDS and Integrating with Flask/SQLAlchemy

### ISSUE THREAD

**Issue by avb7** [NamanSudan/blogFrog#17]
## Introduction
This guide will walk you through the process of setting up a managed PostgreSQL database on AWS RDS and integrating it with your Flask application using Flask-SQLAlchemy. We will also ensure the database credentials are kept secure using environment variables.

## Task Overview

1. Setting up PostgreSQL Database on AWS RDS
2. Creating a PostgreSQL Database Model in Flask using SQLAlchemy
3. Integrating Flask with PostgreSQL Database
4. Securing your database credentials using environment variables

### 1. Setting up PostgreSQL Database on AWS RDS

1. **Log in to your AWS Management Console.**
   
    If you don't have an AWS account, you need to [create one](https://portal.aws.amazon.com/billing/signup#/start).

2. **Go to the RDS service.**
   
    You can find it by typing 'RDS' into the search bar.

3. **Create a new database.**
   
    Click on 'Create database' and choose 'PostgreSQL'.

4. **Configure the database.**
   
    Choose the appropriate settings for your database:
   
   - **Templates:** Choose 'Free tier' if you are just testing or 'Production' for production-ready features.
   - **DB instance identifier:** Enter a name for your database instance.
   - **Master username & password:** Enter a username and password. Remember these credentials as you will need them to connect to the database.
   
    Leave the other settings as default unless you have specific requirements.

5. **Create the database.**
   
    Click 'Create database' at the bottom of the page.

6. **Wait for the database to be set up.**
   
It may take a few minutes. Once the database is set up, you will see its endpoint and port on the details page. Note them down as you will need them to connect to the database.

### 2. Creating a PostgreSQL Database Model in Flask using SQLAlchemy

In your Flask application, create a new file `models.py` in the `website` directory.

### 3. Integrating Flask with PostgreSQL Database

In your Flask application, create a new file `models.py` in the `website` directory.

1. **Define the SQLAlchemy database URI.**

    In `website/__init__.py`, add these lines to configure the SQLALCHEMY_DATABASE_URI with the connection details of your RDS PostgreSQL instance. In the next steps, you will replace the placeholders with your actual credentials, endpoint and port using environment variables set in a file you'll need to create called `.env`:

    ```python
    app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://username:password@database-endpoint:port/database-name'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    ```

2. **Initialize SQLAlchemy.**

    In the same file (`website/__init__.py`), initialize Flask-SQLAlchemy:

    ```python
    from flask_sqlalchemy import SQLAlchemy
    db = SQLAlchemy(app)
    ```

3. **Define the blog post model.**

    In `website/models.py`, define a `Post` model that represents a blog post:

    ```python
    from . import db

    class Post(db.Model):
        id = db.Column(db.Integer, primary_key=True)
        title = db.Column(db.String(100), nullable=False)
        content = db.Column(db.Text, nullable=False)
    ```

4. **Setup Environment Variables.**

     Create a `.env` file in your main project directory, and add your credentials and database connection details there. Make 
     sure to add `.env` to your `.gitignore` file to prevent it from being checked into source control. 

    ```dotenv
    DB_USER='your-username'
    DB_PASS='your-password'
    DB_HOST='database-endpoint'
    DB_PORT='port'
    DB_NAME='database-name'
    ```

5. **Use Environment Variables in your Application.**

    In `website/__init__.py`, use the `os` module to get these environment variables and setup the database connection. 
    Remember to install the `python-dotenv` package for loading environment variables from the `.env` file. Add `python- 
    dotenv` to your `requirements.txt`.

    ```python
    import os
    from dotenv import load_dotenv

    load_dotenv()
    
    DB_USER = os.getenv('DB_USER')
    DB_PASS = os.getenv('DB_PASS')
    DB_HOST = os.getenv('DB_HOST')
    DB_PORT = os.getenv('DB_PORT')
    DB_NAME = os.getenv('DB_NAME')

    app.config['SQLALCHEMY_DATABASE_URI'] = f'postgresql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    ```

4. **Create the database tables.**

    In `website/__init__.py`, after initializing the database and before returning the app, add this line to create all the database tables:

    ```python
    db.create_all()
    ```

## Conclusion

Congratulations! You have successfully set up a managed PostgreSQL database on AWS RDS, integrated it with your Flask application using Flask-SQLAlchemy, and secured your database credentials using environment variables. You are now ready to perform database operations in your Flask application securely.

**Comment by NamanSudan** [comment]
Should we do this now or after building out features like Adding & deleting posts, adding comments, and liking posts?

**Comment by NamanSudan** [comment]
What is the purpose of using the AWS RDS? As per my understanding, it is the following:
1. To learn how to use AWS RDS to create and manage DBs.
2. So that I don't have to store the data on my machine locally, especially for when I allow other users to use the platform (so that they can test out the platform -  be able to create accounts, sign-in, write, post, & edit posts, as well as interact with blogs by liking & commenting on them.

If there are any other reasons, please let me know. My reason for asking this question is two-fold:
1. Curious, in general, as to why we are using it
2. It costs around $16/month so I just wanted to know why it is worth-it

**Comment by avb7** [comment]
No, we should not build the rest of the of the model like Users, etc. until we setup the database properly. 

Learning basic AWS tools is crucial as most companies you work at, they will be using cloud providers such as AWS and you will need some basic understanding to use the tools. RDS allows for quickly setting up databases so there is no developer overhead. 

Instead of building the full model first, it is good to start off small and setup database migrations using Alembic - it’s a python database migration tool (You’ll learn about it next, it is used to maintain db schema changes). This will help you manage model changes as you develop the application further. You can do it locally as well but I think knowing managed and hosted databases is crucial for your backend skills. 

Once you setup the postgres on RDS and configure SQLAlchemy and complete the work for this issue, we can setup alembic in our next issue. 

In terms of cost, choose the cheapest or the Free tier. If it’s costing $16/month, I’ll reimburse you later. But we don’t need to spend more than a month as we’re attempting to finish the project in a week or two.

**Comment by NamanSudan** [comment]
Sounds good on your explanation about the sequence in which features are to be built. You're the coach, and whatever the coach says, goes. Thanks for explaining to me why we're following that process! 

I set-up the RDS Postgres model already. I will have the **integration** of RDS with Flask/SQLAlchemy completed by tomorrow for sure. The defining the Blog Post Model also seems something I will not face much trouble with.

The setting up of environment variables and using them in my application is something **new** for me so it will be a little challenging to do it for the first time. **If needed, I might reach out for clarification/questions**.

About the **database tables** part, I wanted to ask what exactly are those DB tables going to store in them? 

Sounds good on the topic for our next issue. We can sync-up tomorrow night. I will have it done by then by hook or crook. 

Bro, don't worry about reimbursing me for the cost of the RDS thing lol. I agree with you, I don't see us needing to spend more than a month working on this. Moreover, if $16 is the cost I pay to learn how to create and use PostgreSQL DB on AWS RDS (& probably get transferrable knowledge on how to use DBs on AWS RDS), integrate it a Flask/SQLAlchemy application, and build an end-to-end functioning BloggingPlatform that users can use, then lol $16 is a negligible cost for that knowledge & experience.

Let's get it baby
